version: '2'
services:
  app:
    build:
      context: ./docker/7.4
      args:
        NODE_VERSION: 14
        WWWGROUP: "${WWWGROUP}"
    image: galley/app:7.4
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER}"
    volumes:
      - .:/srv/http
      - ../assets/images:/srv/http/webroot/images
    networks:
      - galley
    depends_on:
      - mysql
      - redis
  mysql:
    build:
      context: ./docker/mysql
    image: galley/mysql:5.7
    ports:
      - "${MYSQL_PORT-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - galleymysql:/var/lib/mysql
    networks:
      - galley
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - galleyredis:/data
    networks:
      - galley
networks:
  galley:
    driver: bridge
volumes:
  galleymysql:
    driver: local
  galleyredis:
    driver: local
